baseURL = 'https://chevaltin.github.io/Portfolio/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'iutdelens'

[[menu.main]]
  name = "À propos"
  url = "/a-propos-de"

[[menu.main]]
  name = "Blog"
  url = "/blog"

[[menu.main]]
  name = "Projets"
  url="/projets"

[[menu.social]]
  name = "GitHub"
  url = "https://github.com/VotreCompteGithub"
  pre = "<i class='fab fa-github'></i>"

[[menu.social]]
  name = "Twitter"
  url = "https://twitter.com/Chevalt1"
  pre = "<i class='fab fa-twitter'></i>"

[[menu.footer]]
  name = "À propos"
  url = "/a-propos-de"

[[menu.footer]]
  name = "Blog"
  url = "/blog"

[[menu.footer]]
  name = "Projets"
  url="/projets"

[params]
  author = "Moi"
  authorImage = "Portfolio/images/bother.jpg"

paginate = 6

[[menu.main]]
  name = "Catégories"
  url = "/categories"
